"""update User

Revision ID: 0f907bb055af
Revises: e1f24fd57fa6
Create Date: 2026-03-08 15:06:50.903604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f907bb055af'
down_revision: Union[str, Sequence[str], None] = 'e1f24fd57fa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'super_user',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'super_user',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
