"""update UserAchievements

Revision ID: 2d6f079145c6
Revises: e1ab5473692f
Create Date: 2026-03-03 15:40:57.303637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d6f079145c6'
down_revision: Union[str, Sequence[str], None] = 'e1ab5473692f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_achievements', 'obtained')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_achievements', sa.Column('obtained', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
