"""update UserAchievements

Revision ID: e1ab5473692f
Revises: ed85a311b3e9
Create Date: 2026-03-02 17:15:33.561838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1ab5473692f'
down_revision: Union[str, Sequence[str], None] = 'ed85a311b3e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_user_achievement', 'user_achievements', ['user_id', 'achievement_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_achievement', 'user_achievements', type_='unique')
    # ### end Alembic commands ###
