"""update Achievement, User and add UserAchievements

Revision ID: ed85a311b3e9
Revises: e22e1bb82278
Create Date: 2026-03-02 16:36:38.574989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed85a311b3e9'
down_revision: Union[str, Sequence[str], None] = 'e22e1bb82278'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('obtained', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('achievements', sa.Column('goal', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('achievements_user_id_fkey'), 'achievements', type_='foreignkey')
    op.drop_column('achievements', 'user_id')
    op.drop_column('achievements', 'obtained')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievements', sa.Column('obtained', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('achievements', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('achievements_user_id_fkey'), 'achievements', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('achievements', 'goal')
    op.drop_table('user_achievements')
    # ### end Alembic commands ###
